# Generated by Django 5.2.3 on 2025-07-23 15:08

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='preco_promociona',
            new_name='preco_promocional',
        ),
    ]
